### ISSUE TITLE
Add to installation instruction example for Go 1.17

### ISSUE THREAD

**Issue by oneumyvakin** [rillig/gobco#21]
STEPS TO REPRODUCE
1. Use Go 1.17 

```
go version
go version go1.17 windows/amd64
```

2. `go get github.com/rillig/gobco`

ACTUAL RESULT
```
go get github.com/rillig/gobco
go: downloading github.com/rillig/gobco v0.10.2
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

EXPECTED RESULT
Documentation is aware about Go 1.17 and suggest to use `go install github.com/rillig/gobco@latest`

**Comment by rillig** [comment]
Thank you for the detailed instructions, they made it easy to update the documentation appropriately.
