### ISSUE TITLE
TestMain injection with `_test` package suffix fails

### ISSUE THREAD

**Issue by Evertras** [rillig/gobco#32]
As a minimum way to recreate, have these two files in a directory:

```go
// add.go
package add

func Add(x, y int) int {
    return x + y
}
```

```go
// add_test.go
package add_test

import (
    "os"
    "testing"

    "my-module/pkg/add"
)

func TestMain(t *testing.M) {
    os.Exit(t.Run())
}

func TestAdd(t *testing.T) {
    result := add.Add(1, 2)
    if result != 3 {
        t.Errorf("Got %d but wanted 3", result)
    }
}
```

The error is:

```text
# Cutting out extra bits
$ gobco
./add_test.go:11:10: undefined: gobcoCounts
```

If I remove `TestMain`, it works.  Looking at `gobco -keep`, it looks like `gobcoCounts` is defined in its own file that would use `package add`, not `package add_test`.  We use the `_test` pattern to help enforce testing external behavior, and we can't move TestMain out because it also initializes some connections that are referenced in the actual tests.

**Comment by rillig** [comment]
Thanks for the detailed bug report. I already had all ingredients for fixing this use case, so the actual fix is quite small.

**Comment by Evertras** [comment]
Awesome, thank you so much for an incredibly fast fix!  This has been a very helpful tool for us to deal with auditing.
