### ISSUE TITLE
 cannot use xx (variable of type xx) as type bool in argument to GobcoCover

### ISSUE THREAD

**Issue by 503440692** [rillig/gobco#35]
![image](https://github.com/rillig/gobco/assets/66709975/ad77a277-15e2-4da8-a278-46745dea1a0c)
@rillig thank you for developing the tool: gobco. I have encountered some issues while using the tool. Please refer to the image above for the problem details. It would be appreciated if you could help me resolve this issue.

**Comment by rillig** [comment]
Thank you for reporting this bug, this was indeed an edge case that I hadn't though of.

**Comment by 503440692** [comment]
Awesome, thank you so much for an incredibly fast fix!

**Comment by rillig** [comment]
If the fix works for you, you're lucky. I found some more edge cases in which the instrumented code doesn't compile, such as `cond := MyBool(true) && MyBool(false)`, which originally has type `MyBool` but after instrumentation has type `bool`. I'll have to add proper type resolution to cover this case as well. Stay tuned.
