### ISSUE TITLE
Record statistics on which test covers which condition

### ISSUE THREAD

**Issue by rillig** [rillig/gobco#7]
Assuming that gobco would output which test covers which condition, it would be possible to answer questions like the following:

* For each testee, is there a test that covers all branches of that testee? (minimal unit tests)
* Which tests are necessary to get 100% branch coverage for a given testee?

Implementation ideas:

* Have an additional list of test names for each condition, possibly indirectly by mapping the test name to an `int` for performance.
* Extend the gobco JSON output with this list of tests.

**Comment by rillig** [comment]
Hi @visu-suganya, as you already guessed, `gobco` does not really provide branch coverage but instead condition coverage, despite its name. Up to now, I didn't need branch coverage, as I could tell from the missing conditions what parts of the code are still uncovered. Do you actually need the branch coverage, or is it merely a feeling of "the program is named gobco, so it should report branch coverage"? What use case do you have that requires branch coverage but not condition coverage?

**Comment by visu-suganya** [comment]
@rillig 
Thanks for the immediate reply. 
I need branch coverage result so that developers can easily fix when compared to condition coverage.


In branch coverage, only 2 outcomes totally but in condition coverage, need to cover all the 4 outcomes(it will be difficult to cover all in development period).
So Firstly I need to achieve branch coverage as first step and then go for condition.

**Comment by visu-suganya** [comment]
Hi @rillig 
Is there any possibility to get C1(branch coverage) output?

**Comment by rillig** [comment]
To get C1 output, you can change the method `instrumenter.markConds` by removing the branches for `*ast.UnaryExpr` and `*ast.BinaryExpr`. If that generates the output that you expect, I'll include it in the next release.

**Comment by visu-suganya** [comment]
@rillig Thanks for the implementation and please release the implemented feature so that I can use it.
Thanks a lot.

**Comment by rillig** [comment]
I don't have plans to add this feature anymore. In the past few years I didn't have a need for it.

The comments on this issue are generally off-topic, they are not about finding out which tests cover which code, but about implementing branch coverage in addition to condition coverage.
